firstname = "James";
lastname = "Bond";
fullname = firstname + " " + lastname;
alert(fullname);
isBlah = confirm("input something");
document.write(isBlah);
NodeMine = document.createElement("h1");
textBall = document.createTextNode("this is a baaaal");
NodeMine.appendChild(textBall);
document.body.appendChild(NodeMine);
document.body.firstChild.appendChild(textBall);
console.log(fullname);